name: Continuous integration and deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

jobs:
  test:
    name: Run tests and upload coverage
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm test
    - name: Upload coverage
      uses: coverallsapp/github-action@v1.1.2
      with:
        path-to-lcov: ./test/coverage/lcov.info
        github-token: ${{ secrets.GITHUB_TOKEN }}
  npm:
    name: Publish to npm
    if: github.event_name == 'release'
    needs: test
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        registry-url: https://registry.npmjs.org
    - name: Install dependencies
      run: npm ci
    - name: Publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  gpr:
    name: Publish to GitHub Packages
    if: github.event_name == 'release'
    needs: [test, npm]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        registry-url: https://npm.pkg.github.com
        scope: '@luavixen'
    - name: Install dependencies
      run: npm ci
    - name: Publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
